version: "2.3"
services:

  mongo:
    image: mongo:4.2.0
    mem_limit: 700M
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:0.54.0
    mem_limit: 200M
    restart: always
    depends_on:
      - mongo
    ports:
      - "28081:8081"                                        # MONGO   http://localhost:28081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: cobalt
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 111
      ME_CONFIG_MONGODB_SERVER: mongo